"""Add thumbnail_url to partners

Revision ID: 397070310ac7
Revises: 0001
Create Date: 2025-08-11 14:03:01.291179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397070310ac7'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bags', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_bags_id'), 'bags', ['id'], unique=False)
    op.add_column('partners', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_column('partners', 'thumbnail_url')
    op.drop_index(op.f('ix_bags_id'), table_name='bags')
    op.drop_column('bags', 'thumbnail_url')
    # ### end Alembic commands ###
